'use strict';

/**
 * Static asset provider. Two modes:
 *
 *  1. Bundled/SEA mode: `dist/embedded-assets.js` exists (generated by
 *     `scripts/build.js`) and exports a { path: base64 } map. Used when the app
 *     is packaged into a single portable executable — no filesystem layout needed.
 *
 *  2. Dev mode: read files directly from ../public.
 *
 * The server calls getAsset('/index.html') and gets back a Buffer or null.
 */

const fs = require('fs');
const path = require('path');

// Detect if we're running inside a Node SEA (single executable). In that case
// there's no filesystem layout, so we MUST use the embedded assets. In plain dev
// runs we prefer reading public/ from disk so live edits show up without a rebuild.
let isSea = false;
try {
  isSea = require('node:sea').isSea();
} catch {
  isSea = false;
}

let embedded = null;
try {
  // Present in bundled builds (and inlined into the SEA bundle). Guarded so plain
  // dev runs without a build don't crash.
  // eslint-disable-next-line global-require, import/no-unresolved
  embedded = require('../dist/embedded-assets.js');
} catch {
  embedded = null;
}

const PUBLIC_DIR = path.join(__dirname, '..', 'public');

// Use embedded assets when running as a packaged binary, or as a fallback if the
// public/ directory isn't available.
const useEmbedded = !!(embedded && embedded.assets) && (isSea || !fs.existsSync(PUBLIC_DIR));

function getAsset(urlPath) {
  let p = urlPath;
  if (p === '/' || p === '') p = '/index.html';

  if (useEmbedded) {
    const b64 = embedded.assets[p];
    if (b64 == null) return null;
    return Buffer.from(b64, 'base64');
  }

  // Dev: read from disk with traversal guard.
  const filePath = path.normalize(path.join(PUBLIC_DIR, p));
  if (!filePath.startsWith(PUBLIC_DIR)) return null;
  try {
    return fs.readFileSync(filePath);
  } catch {
    return null;
  }
}

function isEmbedded() {
  return useEmbedded;
}

module.exports = { getAsset, isEmbedded };
