'use strict';

/**
 * Portable build for the MSP Pipeline Dashboard.
 *
 * Produces:
 *   dist/embedded-assets.js  — base64 map of public/* (embedded in the bundle)
 *   dist/bundle.js           — single-file CommonJS bundle of the whole server
 *   dist/msp-pipeline-dashboard (via scripts/package-sea.sh) — SEA executable
 *
 * The bundler is intentionally tiny: it walks require('./x') / require('../x')
 * graphs starting from server/index.js, inlines each module into a synthetic
 * module registry, and leaves Node core modules (http, fs, path, https, url) as
 * real requires. No third-party tooling needed — keeps the build hermetic.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const PUBLIC = path.join(ROOT, 'public');
const ENTRY = path.join(ROOT, 'server', 'index.js');

fs.mkdirSync(DIST, { recursive: true });

/* ---------- 1. Embed public assets ---------- */
function buildAssets() {
  const assets = {};
  for (const name of fs.readdirSync(PUBLIC)) {
    const full = path.join(PUBLIC, name);
    if (fs.statSync(full).isFile()) {
      assets['/' + name] = fs.readFileSync(full).toString('base64');
    }
  }
  const out =
    '// AUTO-GENERATED by scripts/build.js. Do not edit.\n' +
    'module.exports = { assets: ' +
    JSON.stringify(assets) +
    ' };\n';
  fs.writeFileSync(path.join(DIST, 'embedded-assets.js'), out);
  return Object.keys(assets);
}

/* ---------- 2. Bundle the CommonJS module graph ---------- */
const CORE = new Set(['http', 'https', 'fs', 'path', 'url', 'os', 'crypto', 'events', 'stream', 'util']);

function resolve(fromFile, req) {
  // Only bundle relative requires; leave core modules alone.
  if (!req.startsWith('.')) return null;
  let target = path.resolve(path.dirname(fromFile), req);
  if (fs.existsSync(target) && fs.statSync(target).isFile()) return target;
  if (fs.existsSync(target + '.js')) return target + '.js';
  if (fs.existsSync(path.join(target, 'index.js'))) return path.join(target, 'index.js');
  return null;
}

function bundle() {
  const modules = {}; // id -> source
  const idFor = (abs) => path.relative(ROOT, abs).split(path.sep).join('/');
  const seen = new Set();

  function walk(file) {
    const id = idFor(file);
    if (seen.has(id)) return;
    seen.add(id);
    let src = fs.readFileSync(file, 'utf8');

    // Find require('...') calls, rewrite relative ones to registry ids.
    src = src.replace(/require\(\s*(['"])([^'"]+)\1\s*\)/g, (m, q, req) => {
      if (!req.startsWith('.')) return m; // core / node_modules stay literal
      const abs = resolve(file, req);
      if (!abs) {
        // Optional deps (e.g. ../dist/embedded-assets.js) may not exist at bundle
        // time; keep them as a guarded runtime require via the registry helper.
        return `__mspRequire(${JSON.stringify(req)}, ${JSON.stringify(idFor(file))})`;
      }
      walk(abs);
      return `__mspRequire(${JSON.stringify(idFor(abs))}, ${JSON.stringify(idFor(file))})`;
    });

    modules[id] = src;
  }

  walk(ENTRY);

  const registry = Object.entries(modules)
    .map(
      ([id, src]) =>
        `__mspModules[${JSON.stringify(id)}] = function(module, exports, __mspRequire){\n${src}\n};`
    )
    .join('\n');

  const runtime = `
'use strict';
const __mspModules = {};
const __mspCache = {};
function __mspRequire(id, fromId){
  // Relative id already resolved to a registry key at build time.
  if (__mspModules[id]) {
    if (__mspCache[id]) return __mspCache[id].exports;
    const module = { exports: {} };
    __mspCache[id] = module;
    __mspModules[id](module, module.exports, __mspRequire);
    return module.exports;
  }
  // Not in registry: try a real require relative to CWD (optional deps).
  try { return require(id); } catch (e) { return {}; }
}
${registry}
// Kick off the entry module.
__mspRequire(${JSON.stringify(idFor(ENTRY))});
`;

  fs.writeFileSync(path.join(DIST, 'bundle.js'), runtime);
  return Object.keys(modules);
}

const assetNames = buildAssets();
const moduleNames = bundle();

console.log('[build] embedded assets:', assetNames.join(', '));
console.log('[build] bundled modules:', moduleNames.length);
console.log('[build] wrote dist/embedded-assets.js and dist/bundle.js');
